controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\ReportForm;
use yii\web\UploadedFile;

class SiteController extends Controller
{

    private $saveDir = 'uploads';

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'reports'],
                'rules' => [
                    [
                        'actions' => ['logout', 'reports'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionReports() {

        $retData = [];
        $model = new ReportForm();
        
        if(Yii::$app->request->isPost) {
            $model->file = UploadedFile::getInstance($model, 'file');

            if($model->file && $model->validate()) {
                $graph = [];

                $model->file->saveAs($this->saveDir . '/' . $model->file->baseName . '.' . $model->file->extension);

                $spreadsheet = \PhpOffice\PhpSpreadsheet\IOFactory::load($this->saveDir . '/' . $model->file->baseName . '.' . $model->file->extension);

                // TODO: Get a count of the sheets in the spread sheet and add validation accordingly.
                $spreadsheet->setActiveSheetIndex(0);
                $graph['title'] = array(0, $spreadsheet->getActiveSheet()->toArray(null, true, true, true))[1][1]['A'];

                $spreadsheet->setActiveSheetIndex(1);
                $spreadsheetData = array($spreadsheet->getActiveSheet()->toArray(null, true, true, true))[0];

                $graph['valueLabel'] = $spreadsheetData[1]['A'];
                $graph['unitLabel'] = $spreadsheetData[1]['B'];

                $graph['data'] = [];

                $totalCount = array_sum(array_column($spreadsheetData, 'A'));

                for($i = 2; $i<=count($spreadsheetData); $i++) {
                    if(null != $spreadsheetData[$i]['A']) {
                        $graph['data'][] = [
                            'name' => [$spreadsheetData[$i]['B']],
                            'y' => ( $spreadsheetData[$i]['A'] / $totalCount ) * 100,
                            'sliced' => true,
                            'selected' => false,
                            ];
                    }
                }
            }
        }

        return $this->render('reports', [
                    'model' => $model,
                    'graph' => $graph
                ]);
    }


    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?php $this->registerCsrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
        <?php $this->beginBody() ?>

        <div class="wrap">
            <?php
            NavBar::begin([
                'brandLabel' => Yii::$app->name,
                'brandUrl' => Yii::$app->homeUrl,
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            ///////////////////////////////////////////////

            $navItems=[
                ['label' => 'Home', 'url' => ['/site/index']],
                ['label' => 'Reports', 'url' => ['/site/reports']]
            ];
            if (Yii::$app->user->isGuest) {
                array_push($navItems,['label' => 'Sign In', 'url' => ['/user/login']],['label' => 'Sign Up', 'url' => ['/user/register']]);
            } else {
                array_push($navItems,['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
                'url' => ['/site/logout'],
                'linkOptions' => ['data-method' => 'post']]
                );
            }
            echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => $navItems,
            ]);

            ///////////////////////////////////////////////
            NavBar::end();
            ?>

            <div class="container">
                <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
                <?= Alert::widget() ?>
                <?= $content ?>
            </div>
        </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

            <p class="pull-right"><?= Yii::powered() ?></p>
        </div>
    </footer>

    <?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>